baseURL = 'https://danilka4.github.io/'
languageCode = 'en-us'
title = 'Website of Daniel Palamarchuk'
theme = 'blackburn'
[Params]
    subtitle = "Personal Website"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        pre = "<i class='fas fa-home'></i>"
        weight = 1
        identifier = "about"
        url = "/"
    [[menu.main]]
        name = "Projects"
        pre = "<i class='fas fa-code'></i>"
        weight = 2
        identifier = "projects"
        url = "/projects/"
    [[menu.main]]
        name = "CV"
        pre = "<i class='fa fa-list-ul'></i>"
        weight = 3
        identifier = "Curriculum Vitae"
        url = "/files/cv.pdf"
    [[menu.main]]
        name = "Hobbies"
        pre = "<i class='fas fa-book-reader'></i>"
        weight = 4
        identifier = "hobbies"
        url = "/hobbies/"

[social]
    linkedin = "daniel-palamarchuk"
    github   = "danilka4"
    instagram= "daniel.palamarchuk"
