baseURL = 'https://danilka4.github.io/'
languageCode = 'en-us'
title = 'Website of Daniel Palamarchuk'
theme = 'blackburn'

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
